### ISSUE TITLE
Error while loading plugin

### ISSUE THREAD

**Issue by erralb** [jessedobbelaere/ckeditor-iconfont#1]
Hi,

When I try to load the plugin, i get the error :

```
Uncaught TypeError: Cannot read property 'icons' of null
```

I've added the plugin in my ckeditor config.js file like this :

```
config.extraPlugins = 'iconfont';
```

Do you have an idea of what's wrong? I am using CKEditor 4.2.2

**Comment by jessedobbelaere** [comment]
Did you copy&paste the folder images with a tiny icon/button in it? This guy had the same issue and it was fixed by adding the missing files https://github.com/w8tcha/CKEditor-oEmbed-Plugin/issues/34
